import { StyleSheet } from "react-native";
import theme from "../../constants/theme.js";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background,
    },
    scrollContent: {
        paddingHorizontal: theme.spacing.md,
        paddingTop: 56,
        paddingBottom: 110,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: theme.spacing.lg,
    },
    title: {
        color: theme.colors.text,
        fontFamily: theme.fonts.heading,
        fontSize: theme.fontSize.xxl,
    },
    subtitle: {
        color: theme.colors.textSecondary,
        fontFamily: theme.fonts.body,
        fontSize: theme.fontSize.sm,
        marginTop: 2,
    },
    editIconButton: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 44,
        height: 44,
        borderRadius: theme.radius.pill,
        backgroundColor: '#EAF6ED',
    },
    profileCard: {
        alignItems: 'center',
        backgroundColor: theme.colors.surface,
        borderRadius: theme.radius.lg,
        padding: theme.spacing.lg,
        borderWidth: 1,
        borderColor: theme.colors.border,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 3,
    },
    avatarWrapper: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 96,
        height: 96,
        borderRadius: 48,
        backgroundColor: theme.colors.primary,
        overflow: 'hidden',
        borderWidth: 4,
        borderColor: '#EAF6ED',
    },
    avatarImage: {
        width: '100%',
        height: '100%',
    },
    profileName: {
        color: theme.colors.text,
        fontFamily: theme.fonts.heading,
        fontSize: theme.fontSize.xl,
        marginTop: theme.spacing.md,
        textAlign: 'center',
    },
    profileNickname: {
        color: theme.colors.primary,
        fontFamily: theme.fonts.medium,
        fontSize: theme.fontSize.sm,
        marginTop: 2,
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginTop: theme.spacing.sm,
    },
    locationText: {
        color: theme.colors.textSecondary,
        fontFamily: theme.fonts.body,
        fontSize: theme.fontSize.sm,
    },
    editButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: theme.spacing.sm,
        minWidth: 180,
        marginTop: theme.spacing.lg,
        paddingHorizontal: theme.spacing.lg,
        paddingVertical: 12,
        borderRadius: theme.radius.pill,
        backgroundColor: theme.colors.primary,
    },
    editButtonText: {
        color: theme.colors.white,
        fontFamily: theme.fonts.button,
        fontSize: theme.fontSize.md,
    },
    section: {
        marginTop: theme.spacing.lg,
    },
    sectionTitle: {
        color: theme.colors.text,
        fontFamily: theme.fonts.title,
        fontSize: theme.fontSize.lg,
        marginBottom: theme.spacing.sm,
    },
    infoCard: {
        backgroundColor: theme.colors.surface,
        borderRadius: theme.radius.lg,
        borderWidth: 1,
        borderColor: theme.colors.border,
        paddingHorizontal: theme.spacing.md,
    },
    infoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: theme.spacing.md,
    },
    infoIcon: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 42,
        height: 42,
        borderRadius: theme.radius.md,
        backgroundColor: '#EAF6ED',
    },
    infoContent: {
        flex: 1,
        marginLeft: theme.spacing.md,
    },
    infoLabel: {
        color: theme.colors.textSecondary,
        fontFamily: theme.fonts.body,
        fontSize: theme.fontSize.xs,
    },
    infoValue: {
        color: theme.colors.text,
        fontFamily: theme.fonts.semiBold,
        fontSize: theme.fontSize.md,
        marginTop: 2,
    },
    divider: {
        height: 1,
        marginLeft: 58,
        backgroundColor: theme.colors.border,
    },
    logoutButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: theme.colors.surface,
        borderRadius: theme.radius.lg,
        borderWidth: 1,
        borderColor: '#F4D7D5',
        padding: theme.spacing.md,
    },
    logoutContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    logoutIcon: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 42,
        height: 42,
        borderRadius: theme.radius.md,
        backgroundColor: '#FDEDEC',
        marginRight: theme.spacing.md,
    },
    logoutTitle: {
        color: theme.colors.error,
        fontFamily: theme.fonts.semiBold,
        fontSize: theme.fontSize.md,
    },
    logoutSubtitle: {
        color: theme.colors.textSecondary,
        fontFamily: theme.fonts.body,
        fontSize: theme.fontSize.xs,
        marginTop: 2,
    },
    versionText: {
        color: '#AAAAAA',
        fontFamily: theme.fonts.body,
        fontSize: theme.fontSize.xs,
        textAlign: 'center',
        marginTop: theme.spacing.xl,
    },
});
